### ISSUE TITLE
Error on emacs 25.3

### ISSUE THREAD

**Issue by arteenfox** [hlissner/emacs-pug-mode#22]
Error on emacs 25.3.1
`Error during redisplay: (jit-lock-function 1) signaled (no-catch --cl-block-pug-extend-region-- nil)`

**Comment by hlissner** [comment]
This has been fixed since https://github.com/hlissner/emacs-pug-mode/commit/cc735b61756c923bc1bca218c40db580d6dc6560 (Sep 13). I suspect you've installed pug-mode through MELPA Stable, which did not update my plugin when I moved the 1.0.5 tag a couple months ago.

In any case, I've bumped it to 1.0.7. Once MELPA stable picks this up, your issue should be fixed.
